### ISSUE TITLE
how generate packed_trx ?

### ISSUE THREAD

**Issue by IsQiao** [BitsumFoundation/NEos#1]
i want use simplewalllet,
when i verify the sign,
i set  packed_trx  variable is  [ timestamp + account + uuID + ref];
but throw a exception ,like this:
System.FormatException: 'Could not find any recognizable digits.'
so,what kind of value can be set in packed_trx variable?

`var data = "1544089913" + "qinxi1" + "bd0b2b49-94ee-454b-a4d5-c078d6145282" + "TokenPocket";`
            `var r = keyPair.VerifySignature("aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906", data, "SIG_K1_K1VkAzpqsN");`

**Comment by i4egod** [comment]
Hi. You should use client.CreateTransaction(actions) to create transaction and client.SignTransaction(tx, pvt) to create signed transaction and after that you can push it. Check this example:
           

            TransferAction a = new TransferAction()
            {
                Account = "eosio.token",
                Data = new TransferData()
                {
                    From = "from",
                    To = "to",
                    Quantity = new Currency("1.0000 EOS"),
                    Memo = "test"
                }
            };

            a.Authorization = new List<Authorization>()
            {
                new Authorization()
                {
                    Actor = a.Data.From,
                    Permission = "active"
                }
            };

            var actions = new List<IAction>
            {
                a
            };

            PrivateKey pvt = new PrivateKey(JunglePrivateKey);

            var tx = client.CreateTransaction(actions).Result;
            Trace.WriteLine(tx.ToJson());

            var stx = client.SignTransaction(tx, pvt).Result;
            Trace.WriteLine(stx.ToJson());

            var txid = client.PushTransaction(stx).Result;
            Trace.WriteLine($"\nTX Hash: {txid}");`
